### ISSUE TITLE
Document team norms around versioning and testing

### ISSUE THREAD

**Issue by oates** [defenseunicorns/uds-software-factory#10]
To rebuild our foundation and question previous assumptions we should redo the ADRs that were all grouped together in a single ADR in the past here https://github.com/defenseunicorns/uds/blob/main/docs/adr/0006-uds-software-factory.md

Success Criteria:
- All ADRs found in the list above are documented here https://github.com/defenseunicorns/uds-software-factory/tree/main/adr
```[tasklist]
### Tasks
- [ ] SWF Testing
- [ ] SWF Versioning Scheme
```

**Comment by zachariahmiller** [comment]
🫡

**Comment by zachariahmiller** [comment]
I'm on the hook for these:

![Image](https://github.com/defenseunicorns/uds-software-factory/assets/71521611/706d5568-8e4a-4265-8dfe-595464c19639)

Happy to help with the doc tools one as needed.

**Comment by naveensrinivasan** [comment]
Before creating these ADR's it would help to define the problem statement as to what these are solving specifically. 

`WHAT` and `WHY`? 

Including it in the issue would be helpful if it is already there.

**Comment by zachariahmiller** [comment]
Pretty sure that is the "context" part of the ADR

**Comment by naveensrinivasan** [comment]
> Pretty sure that is the "context" part of the ADR

Great! Can we also please include that part of the GH issue? It helps to read the issue and then get into the doc.

**Comment by zachariahmiller** [comment]
You are welcome to add additional context to the issue

**Comment by Racer159** [comment]
Runner ADR issue moved here: https://github.com/defenseunicorns/uds-package-gitlab-runner/issues/48
