### ISSUE TITLE
Validate commitlint component on gitlab

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#106]
Issue to port commitlint functionality we use in github to gitlab without regressions in functionality

```[tasklist]
### Tasks
- [x] port workflow and tasks
```

**Comment by zachariahmiller** [comment]
gitlab doesnt have the same triggers as github and as such as it stands today we cannot enable the functionality where when someone changes the title of a PR it will retrigger the commitlint pipeline. 

This leaves us with essentially 3 options:
1. document this shortcoming and try to guide behavior
2. Build a custom webhook receiver that receives the webhook only merge request events and then executes the commitlint pipeline to run again via api request to the pipelines api.
3. write a centralized pipeline job/project that runs a a very short schedule and queries all open mrs and re-kicks the commitlint job if its not complaint. This has numerous limitations including limitations in gitlab scheduling using sidekiq for short durations, causes additional compute overhead and overhead on the web service for ci running the checks and still is not remotely close to properly enforcing as there is no actual trigger aside from the schedule.


As such, we will stick with option 1 in the short term and evaluate our options further once we are able to get folks onboarded to using gitlab.

**Comment by Racer159** [comment]
4th option would be exploring a FaaS solution such as Knative https://knative.dev/docs/ (which may be more flexible for others as well)

**Comment by zachariahmiller** [comment]
> 4th option would be exploring a FaaS solution such as Knative https://knative.dev/docs/ (which may be more flexible for others as well)

yes which i love as a long term solution with additional value add for our platform!

**Comment by oates** [comment]
Agree on going with short term solution #1 for now and getting back to the other solutions post migration
