### ISSUE TITLE
Determine and align on `registry1` testing behavior

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-software-factory#3]
### Describe what should be investigated or refactored
`registry1` tests run on every PR run but can be very flakey in testing and adds complexity and cost to PR runs.  We should determine a decent strategy for handling this in Software Factory so that we can get fast / cheap feedback but also so that we do not break any releases.

### Links to any relevant code
https://github.com/defenseunicorns/uds-package-mattermost/blob/main/.github/workflows/test.yaml#L29

### Additional context
`registry1` goes down reasonably often requiring forced re-runs of tests, and eating up time in the review process (costing man hours and compute time given we use paid runners).  A potential way to fix this would be to implement something like:

1. Do not run the `registry1` tests unless the registry1 specific values files or `zarf.yaml` components change (i.e. chart versions)
2. (potentially) Run `registry1` tests on an interval (nightly?) to see get a heads up if images are borked
3. Always run `registry1` tests on releases.

**Comment by zachariahmiller** [comment]
@oates @Racer159 we agreed to close this since we are already doing this testing at the package level and aligned on approach for integration repo level right?
