### ISSUE TITLE
Spike: Evaluate swapping Maru with Dagger / Tekton

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-software-factory#57]
### Is your feature request related to a problem? Please describe.

We should evaluate the benefits of continuing our pipeline component implementation with Maru runner vs using an existing tool like Dagger or Tekton.

### Describe the solution you'd like

We should swap Maru for Dagger and Tekton within the pipeline vertical slice and document our decision in an ADR and the design document being worked in #43 .

### Additional context

Both of these technologies were previously evaluated but we should reevaluate changes that have occurred in the past several months as both projects have evolved quite a lot.

**Comment by Racer159** [comment]
Marked as blocked on https://github.com/defenseunicorns/uds-package-gitlab-runner/issues/87 and https://github.com/defenseunicorns/uds-software-factory/issues/55 as these will be needed to have a practical example to test with.

**Comment by docandrew** [comment]
The HNCD team is happy to share some lessons learned from our experience with Dagger if this ticket is unblocked or reconsidered in the future.

**Comment by jeff-mccoy** [comment]
@Racer159 please include me in this decision if it ever comes back up, I'll want final approval.

**Comment by Racer159** [comment]
http://concord.walmartlabs.com/ could be another set of tooling to look into

**Comment by Racer159** [comment]
On Dagger specifically we likely will run into docker socket issues with its container orchestration and may run into the same with Tekton - a lot of where we are going is toward ephemeral VMs since we do so much container work that we will need to strongly consider this in this ADR (see @docandrew for dagger experience)
