### ISSUE TITLE
List of tools we plan to use in our Pipelines

### ISSUE THREAD

**Issue by oates** [defenseunicorns/uds-software-factory#67]
### Is your feature request related to a problem? Please describe.
To begin understanding the tools we will use in our pipelines as well as communicate to external teams like marketing we need to begin identifying the tools we plan to use in our pipeline for various stages such as Build, Test, etc. 

### Describe the solution you'd like

We need to begin listing various tools we want to use in our pipelines that we would build components for and message externally. This could be done via a spike for an initial list and then rolled into separate issues to build components for. 

We need to maintain a list of the various technologies or components we maintain for our users.

Link to Miro exercise with folks on what we think is most used or should be included found here: https://defenseunicorns.miro.com/app/board/uHjVOftl710=/

**Comment by Racer159** [comment]
Should be doc'ed in Coda

**Comment by oates** [comment]
List is currently documented internally here https://coda.io/d/Product_dGmk3eNjmm8/Pipeline-Technologies_suBoV#_lu12X
