### ISSUE TITLE
Replace dev-redis package in the swf bundles with uds-package-valkey

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#68]
### Describe what should be investigated or refactored
Now that we have a uds package for [valkey](https://github.com/defenseunicorns/uds-package-valkey), we should replace the [dev-redis](https://github.com/defenseunicorns/uds-software-factory/blob/8651574405509ee34995ed51bc3b59a9771ada11/bundles/k3d-demo/uds-bundle.yaml#L68) package being pulled into the bundles.

**Comment by Racer159** [comment]
Completed in https://github.com/defenseunicorns/uds-software-factory/pull/78
