### ISSUE TITLE
Remove `.vscode` folders from individual repositories and instead centralize into `uds-common`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-software-factory#72]
### Describe what should be investigated or refactored

Currently there are `.vscode` folders in the root of some SWF repos.  These get out of sync and can cause issues overriding other settings a user may have on their system.  Instead we should `.gitignore` this folder and centralize a common `.vscode/settings` file in `uds-common` along with docs on how to install it and configure settings for working with UDS in VS Code.

### Links to any relevant code
https://github.com/defenseunicorns/uds-package-gitlab/tree/main/.vscode
https://github.com/defenseunicorns/uds-package-gitlab-runner/tree/main/.vscode
https://github.com/defenseunicorns/uds-package-postgres-operator/tree/main/.vscode
https://github.com/defenseunicorns/uds-package-valkey/tree/main/.vscode

### Additional context

This would also help others who use different IDEs to have a place to centralize their own configs.

**Comment by zachariahmiller** [comment]
Documentation of configuration of IDE (for vscode) for uds-common https://github.com/defenseunicorns/uds-common/pull/165

Ideally folks using other IDEs can provide the documentation for them as needed.
